version: "3"

services:
  web:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    # command: tail -f /dev/null
    # command: bash
    command: /code/entrypoint.sh
    volumes:
      - .:/code/
