# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dm.defaultable.stuff
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=0)),
                ('init', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.ForeignKey(default=functools.partial(dm.defaultable.stuff.get_or_create_multi_default, *(b'ModelX', b'dm', 1), **{}), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='x1', to='dm.ModelX')),
                ('x2', models.ForeignKey(default=functools.partial(dm.defaultable.stuff.get_or_create_multi_default, *(b'ModelX', b'dm', 2), **{}), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='x2', to='dm.ModelX')),
            ],
        ),
    ]
