# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dm.defaultable.stuff
import dm.models_shared
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=0)),
                ('dummy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(blank=True, default='', upload_to=dm.models_shared.upload_to)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.ForeignKey(default=functools.partial(dm.defaultable.stuff.get_or_create_multi_default, *(b'ModelX', b'dm', 1), **{}), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='x1', to='dm.ModelX')),
                ('x2', models.ForeignKey(default=functools.partial(dm.defaultable.stuff.get_or_create_multi_default, *(b'ModelX', b'dm', 2), **{}), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='x2', to='dm.ModelX')),
            ],
        ),
        migrations.AddField(
            model_name='modelx',
            name='y',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dm.ModelY'),
        ),
    ]
