# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dm.defaultable.stuff
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='x3',
            field=models.ForeignKey(default=functools.partial(dm.defaultable.stuff.get_or_create_multi_default, *(b'ModelX', b'dm', 3), **{}), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='x3', to='dm.ModelX'),
        ),
    ]
