# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelx',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelx',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
