# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_auto_20190929_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelx',
            name='f',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
