# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_modelx_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelx',
            name='i',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
