# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0004_modelx_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelx',
            name='f',
            field=models.FileField(blank=True, default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='modelx',
            name='i',
            field=models.ImageField(blank=True, default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='modelx',
            name='init',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='modelx',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
